// <auto-generated />
using System;
using Api_Development.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api_Development.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217120847_optimizar nomes dos modelos")]
    partial class optimizarnomesdosmodelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api_Development.Models.Domain.Caminhada", b =>
                {
                    b.Property<Guid>("CaminhadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhadaImagemUrl")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DificuldadeId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("uuid");

                    b.HasKey("CaminhadaId");

                    b.HasIndex("DificuldadeId");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Caminhadas");
                });

            modelBuilder.Entity("Api_Development.Models.Domain.Dificuldade", b =>
                {
                    b.Property<Guid>("DificuldadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DificuldadeId");

                    b.ToTable("Dificuldades");

                    b.HasData(
                        new
                        {
                            DificuldadeId = new Guid("d1bfbf8e-9c3a-4c5e-9a1b-1a2b3c4d5e6f"),
                            Nome = "Fácil"
                        },
                        new
                        {
                            DificuldadeId = new Guid("e2c1a9f7-8b4d-4f6e-9b2c-2b3c4d5e6f70"),
                            Nome = "Médio"
                        },
                        new
                        {
                            DificuldadeId = new Guid("f3d2b8c6-7a5e-4a7f-9c3d-3c4d5e6f7a8b"),
                            Nome = "Difícil"
                        });
                });

            modelBuilder.Entity("Api_Development.Models.Domain.Regiao", b =>
                {
                    b.Property<Guid>("RegiaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagemRegiaoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RegiaoId");

                    b.ToTable("Regioes");

                    b.HasData(
                        new
                        {
                            RegiaoId = new Guid("a1b2c3d4-e5f6-4a8b-9c0d-1e2f3a4b5c6d"),
                            Codigo = "Nor",
                            ImagemRegiaoUrl = "https://example.com/images/north.jpg",
                            Nome = "Norte"
                        },
                        new
                        {
                            RegiaoId = new Guid("b2c3d4e5-f6a7-4b9c-0d1e-2f3a4b5c6d7e"),
                            Codigo = "Sul",
                            ImagemRegiaoUrl = "https://example.com/images/south.jpg",
                            Nome = "Sul"
                        },
                        new
                        {
                            RegiaoId = new Guid("c3d4e5f6-a7b8-4c0d-1e2f-3a4b5c6d7e8f"),
                            Codigo = "Oes",
                            ImagemRegiaoUrl = "https://example.com/images/East.jpg",
                            Nome = "Oeste"
                        },
                        new
                        {
                            RegiaoId = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            Codigo = "Est",
                            ImagemRegiaoUrl = "https://example.com/images/West.jpg",
                            Nome = "Este"
                        });
                });

            modelBuilder.Entity("Api_Development.Models.Domain.Caminhada", b =>
                {
                    b.HasOne("Api_Development.Models.Domain.Dificuldade", "Dificuldade")
                        .WithMany()
                        .HasForeignKey("DificuldadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_Development.Models.Domain.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dificuldade");

                    b.Navigation("Regiao");
                });
#pragma warning restore 612, 618
        }
    }
}
